name: Hello World Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello World
        run: echo "hello world"
